### ISSUE TITLE
not work for   oculus quest or pico VR.

### ISSUE THREAD

**Issue by v23v** [RimuruDev/UnitySkipSplashScreen#2]
For VR app,  the  unity logo  still exist when start the game.  This  only  work  for cellphone app

**Comment by RimuruDev** [comment]
Thank you, I will fix it soon.

**Comment by RimuruDev** [comment]
Thank you for your patience and for bringing this issue to our attention. The issue has been fixed and it should now work on Oculus Quest. Commit SHA: 13e57bdfb7608c75d0b7604c0f9c76d568bb71af.

If you encounter any further problems, please don't hesitate to report them.

**Comment by v23v** [comment]
Thanks for your reply and for taking the time to fix this, I just tried it  on the quest2 and it still doesn't work. The unity version I use is 2022.3.30f1.
